crawler:
  url_extractor:
    sources:
      scmp_urls:
        output_dir: "data/raw/scmp/urls"
        base_url: "https://www.scmp.com/"
        targets:
          - xpath: "//a[contains(., 'China')]"
            url: "https://www.scmp.com/"
          - xpath: "//a[contains(., 'China')]"
            url: "https://www.scmp.com/"

  html_crawler:
    sources:
      scmp_htmls:
        output_dir: "data/raw/scmp/html"
        base_url: "https://www.scmp.com/"
        input_file: "data/raw/scmp/urls/scmp_urls.json"
        resumable: True
        targets:
          - xpath: "//article"
            url: "https://www.scmp.com/"

  image_extractor:
    sources:
      scmp_images: # name of source.
        output_dir: "data/raw/scmp/images"
        base_url: "https://www.scmp.com/"
        save_images: true
        targets:
          - xpath: "//img"
            url: "https://www.scmp.com/"

  text_extractor:
    sources:
      scmp_headlines:
        output_dir: "data/raw/scmp/text"
        base_url: "https://www.scmp.com/"
        output_filename: "headlines.json"
        targets:
          - xpath: "//div[@data-qa='Component-Headline']//h2"
            url: "https://www.scmp.com/news/china"
