# Build stage
FROM node:20-alpine as build
WORKDIR /app
COPY frontend/package.json frontend/yarn.lock ./
RUN yarn install
COPY frontend/ ./
# Environment variables will be set at build time
ARG VITE_API_BASE_URL=  # Default to empty for relative URLs
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
RUN yarn build

# Production stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]