services:
  db:
    image: postgres:latest
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: dhg503_db_container
    ports:
      - "54503:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dhg503
      POSTGRES_PASSWORD: dhg503dhg503
      POSTGRES_DB: dhg503
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dhg503 -d dhg503"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - dhg503_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: dhg503_api_container
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: python -m scripts.serve
    networks:
      - dhg503_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_BASE_URL=
    container_name: dhg503_frontend_container
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - dhg503_network

networks:
  dhg503_network:
    driver: bridge

volumes:
  postgres_data:
