services:
  db:
    image: postgres:latest
    build:
      context: .
      dockerfile: Dockerfile.db

    container_name: dhg503_db_container
    ports:
      - "54503:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dhg503
      POSTGRES_PASSWORD: dhg503dhg503
      POSTGRES_DB: dhg503
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dhg503 -d dhg503"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: dhg503_api_container
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: python -m scripts.serve

  frontend:
    image: node:20-alpine
    container_name: dhg503_frontend_container
    working_dir: /app
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - api
    command: sh -c "yarn install && yarn dev --host --mode production"

volumes:
  postgres_data:
